### ISSUE TITLE
AccessMixins: pass object to has_perm(s)

### ISSUE THREAD

**Issue by slafs** [brack3t/django-braces#163]
I have a feature proposal for `AccessMixins` (i.e. `PermissionRequiredMixin` and `MultiplePermissionsRequiredMixin`). 

It would be nice if braces could pass an object while performing `has_perm(s)` checks to achieve [object-level-permissions](https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#handling-object-permissions). This would make a great combo with other apps (like django-guardian or rules or any other) that provide object level permissions checking. Of course I would see this as an opt-in behavior because retrieving an object on a view isn't always that trivial but I guess for 90% of use cases `.get_object()` would be enough. 

What do you think about this?

I would like to make a PR for this but only after some discussion regarding some implementation details (should I use just `self.get_object()` or a custom method that defaults to `self.get_object()` etc.)

**Comment by kennethlove** [comment]
Yes, it should definitely be opt-in. Maybe an extra mixin that adds the object to the permissions check. You could compose those into yet another mixin for people that don't want such a long inheritance chain.

As for getting the object, just use `self.get_object()` since that already exists and is overridable for cases where the standard mechanism doesn't work.

**Comment by chrisjones-brack3t** [comment]
closing very old issues
