### ISSUE TITLE
Maintain GitHub tags

### ISSUE THREAD

**Issue by Skeen** [brack3t/django-braces#230]
Hello,

It appears that the GitHub tags for releases stopped May 31, 2016, while releases on the pip package manager continued.

PyPi announches the latest release as 1.11.0 of 2017-02-01, where's GitHub's most recent release is 1.9.0 of 2016-05-31.

Is there a specific reason why GitHub releases has been dropped from the release cycle? - Is it too much work to include again?

**Comment by browniebroke** [comment]
Looks like the changelog isn't maintained either: https://django-braces.readthedocs.io/en/latest/changelog.html

**Comment by browniebroke** [comment]
Something that happens often to me is to forget to `git push --tags`... Hopefully, that's just what is missing here @PetrDlouhy?

**Comment by browniebroke** [comment]
In case it helps people coming here, here is what I could find by navigating through the history of `braces/__init__.py`:

- 1.13.0: 2158cf3bf2795c6b834731d30b1750441c580a3a (new since previous: https://github.com/brack3t/django-braces/compare/be2be87a7c45d4b340d1a6989e606a84da8d2347...2158cf3bf2795c6b834731d30b1750441c580a3a)
- 1.12.0: be2be87a7c45d4b340d1a6989e606a84da8d2347 (new since previous: https://github.com/brack3t/django-braces/compare/84e36ed17823579aadbd6a0855cf9f8814fd9961...be2be87a7c45d4b340d1a6989e606a84da8d2347)
- 1.11.0: 84e36ed17823579aadbd6a0855cf9f8814fd9961 (new since previous: https://github.com/brack3t/django-braces/compare/deef720f6e6067a88ef79dad44cae026fa0b4bfe...84e36ed17823579aadbd6a0855cf9f8814fd9961)
- 1.10.0: deef720f6e6067a88ef79dad44cae026fa0b4bfe (new since previous: https://github.com/brack3t/django-braces/compare/df5a70256cf7228af32a68a57b6ed9caf93c7db7...deef720f6e6067a88ef79dad44cae026fa0b4bfe)
- 1.9.0: df5a70256cf7228af32a68a57b6ed9caf93c7db7

I'm not 100% sure about the version 1.12.0, as it was updated while updating other things.
